### PR TITLE
Changed time calculation from characters per second to words per minute

### PR DESCRIPTION
**Pull request by MasterOfTheTiger**
I have changed the code to calculate the time to read to use words per minute rather than characters per second. The README.md file is also updated to reflect this change.

To do this I had to rewrite most of that function. The new code is commented similarly as before. 

Note: you may want to change the default words per minute speed, because there is a pretty noticable discrepancy between the old calculation and the new.

### CODE REVIEW

**Comment by davidlday** [comment]
Visually inspected code. Changes look good, but I don't have time to test right now. This should close #83.

**Comment by MasterOfTheTiger** [comment]
@davidlday I looked at that issue, and it seems like that one is referring to tracking user words per minute in writing.

**Comment by davidlday** [comment]
@MasterOfTheTiger  Good point - I asked for clarification on the issue. Now I'm reading it both ways and I'm not sure which is right. 😕

**Comment by davidlday** [comment]
@MasterOfTheTiger - Please resolve the minor conflicts and I'll run tests. Thank you!

**Comment by MasterOfTheTiger** [comment]
@danielbayley Conflicts are resolved now.

**Comment by MasterOfTheTiger** [comment]
@davidlday When will the new changes be released for Atom?

**Comment by davidlday** [comment]
@MasterOfTheTiger Unfortunately, I don't. @OleMchls - thoughts?

**Comment by OleMchls** [comment]
> @MasterOfTheTiger Unfortunately, I don't. @OleMchls - thoughts?

I'll go over all pending issues/discussions today and cut a release afterwards

**Pull request merged**
