### PR TITLE
Added Estimated Time To Read

### PR DESCRIPTION
**Pull request by mpstenson**
Added an estimated time to read display after the word and character count. It's based on the average reading speed of 275 WPM.

### CODE REVIEW

**Comment by nickjj** [comment]
I like this idea. Question for you, what do you think about extending this functionality so that it works for both reading and speaking?

Use case:

- You are creating a presentation and want to get a rough idea of how long sections will take (especially useful if you have your presentation marked with slides, so you can know how long each slide lasts)

I think it might get too crowded to have both read time and speak time output in the status bar, so my proposition would be to always show the estimated read time, with a hover tooltip that shows the speak time length.

What do you think?

**Comment by nesQuick** [comment]
@mpstenson  thank you very much for the contribution, I just checked it out and I like it very much! You could do the project a special favor in updateing the Readme and the screenshot and also adding some explanations on that. Because just having a `x M` in the status bar will be confusing for people.

I also like the idea of @nickjj but don't see this in this PR. But also happy to take such a thing as a PR.

**Comment by brucellino** [comment]
Hi all. I just realised that I need this plugin, and was very happy to see that a PR was open. But now I'm sad because it seems it never got merged. 

Can someone comment on what the status is ? Is there another plugin which does the same, or has this been pulled in some other PR ? 

Thanks ! 
Bruce

**Comment by nesQuick** [comment]
@brucellino please see my comment above https://github.com/nesQuick/atom-wordcount/pull/54#issuecomment-169103081

You could use the fork that proposed that PR or also fork the fork and take care of the remaining todos.

**Comment by X-Raym** [comment]
I also made fork which handles Time evaluation

https://github.com/X-Raym/atom-wordcount

screenshot

(it also add span to be able to target things via CSS, to hide them or change style)

@OleMchls I can propose it as pull request if you like the modifications !

**Comment by OleMchls** [comment]
@X-Raym I think that would be a valuable addition to word-count. However, I think it should come disabled and in a pop-up or alt/shift press toggle. Because I would not want to overload the initial exprieince / information. When one installs word-count. I'd love to see your if you have a good idea on how to solve this.

**Comment by X-Raym** [comment]
@OleMchls I can add simple toggle checboxes for that in word-count action.

Three checkboxes like

- Display Word Count (activated by default)
- Display Character Count (activated by default)
- Display Time Estimation (deactivated by default)

I think the separator logic must also be recoded with a simple CSS rule rather than hardcoded `|` which can't be targeted by CSS.

What do you think ?

**Comment by X-Raym** [comment]
@OleMchls IMHO it would be the opportunity to enhance settings a bit,
for eg, you have a Show bolean for the Price, and a Hide bolean for the characters count. I think having only Show boolean (where True/Checked means displayed) is better than Hide.

Also, the color section could be be set as `color` rather than simply string, so that we have color preview and color picker.

Sounds good to you ?

**Comment by OleMchls** [comment]
@X-Raym that indeed sounds good to me. I'd love to hide options when their _parent_ is not checked. Like not displaying the price per word when that option is not enabled. But IDK if atom support dynamic settings.

**Comment by X-Raym** [comment]
@OleMchls just updated my fork so you can test

https://github.com/X-Raym/atom-wordcount

It has various enhancements :

- classes for the various elements displayed in status bar so that they can have custom styles
- the settings with Show option for all fields, and colors pickers
- the time estimation based on character count

If you like it, I can create a pull request.

**Comment by X-Raym** [comment]
@OleMchls I updated my branch to match last version updates and enhancements. It is ready to be merged, if you are ok with it !

**Comment by X-Raym** [comment]
@OleMchls Done ! I think you can close this pull request cause it is outdated.

**Comment by OleMchls** [comment]
Replaced with #98

**Pull request closed without merging**
